{% set name = "cppunit" %}
{% set version = "1.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://dev-www.libreoffice.org/src/{{ name }}-{{ version }}.tar.gz
  sha256: 3d569869d27b48860210c758c4f313082103a5e58219a7669b52bfd29d674780

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/cppunit/TestFixture.h
    - test -f $PREFIX/lib/libcppunit.a
    - test -f $PREFIX/lib/libcppunit${SHLIB_EXT}    # [unix]

about:
  home: https://freedesktop.org/wiki/Software/cppunit/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'CppUnit is the C++ port of the famous JUnit framework for unit testing'

extra:
  recipe-maintainers:
    - nsoranzo
