travis:
  secure:
    BINSTAR_TOKEN: Cfc/ZXbIg5ovpFwABssbedStYTiSnyryWVxBONYr4GVaqrJ6cKxMA3zcJ+3PSx9MOb0n1ZTXXH2PfqTMPua77L0+ow3u244KrTpOukNKBzXfmJuxC+G+40tgS+jrMagMrDuVUnVW0jgcWJAr5fb6Qu8notOPIB8lg3g3PD2Tr8h2Fljkitrnsod/cLaZxXLfZXBPnYBZMitWZ3PRnWJV6SXdrMTIxyUr9DDw/nMebjHJreIoxUdSeup84cEvS0bCrnGbTb7f00o/0NQWVFNRUsvzAlyJPjomN8tOBZ8TO6nKJK2MPwKSAvtnZdvyElWa5vh+hIFCsy6wFpE7bHX4AHj4Hb/uTwMsJuQ0agIu5hRyaHX/yRZYVSRbK5Z71rPbNxzqVoMbBsNYfkwC5EjDkzS2Sm4w1Muc3vKsxniz76G7C8sDdW+jaJXtw4bYRjxhu57LZIVtdmxY500eOXgWWo5+fh3XcWBD/8mnVjIVBcjap1tFZtevrhC0Fvp7rcNQlJCLAMv+ybJeJxz3JhQxPfFrOD/vi02Z9J0tiRhjS5KLVGYy+4CA7XkQUBX8bzzLJ8x6BFqFgfid3089g+8gLMCWsebkQSXvn1abeX1SY4Xsb08cB7RLr/jacO44nxV2ZTWzIsHTn1q4iJ5hb/Wf65d6SLvnkj63zbo5JoIgz3o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
