travis:
  secure:
    BINSTAR_TOKEN: Qj4N0au2O6poKyhmH7Pgxf8WSXGeMLRExjbGq6poyRgELtv7fMbWqnG9XEKSQhk4LTKJPzCGreLrclrFi+gwpkUaNlkKAOMJvxrWl7WAh8MAbRe0po1B9EjUBghVhX/U4/RXOhNYW3OxlKwDrYo3Zg1jlRgOv5+ob5vWI6njG3C7B2RdmxJIDQZLLk/x39ghTZrQW6dR3ykeMYEMCXzhaGBIXgwJ5jxI4GjLbQkWF0fVB1YEMOaw3x5GST3lAmhVHBY8qztbBWadjQ/c/twDFm397XpP933ix2jUOYXAHh+tUBkhqNFoNo/D8HG0sy83CkeHMgT0EFVnoHQf8bVL37gCqHQWETrLtNzQ9wYTLMREDmWMHbe0n9SZvzOBDHO5wZwDda5WNLl2LRpKvk24XPX4U3bVWewwAeOU/RWIbZoJK3kKoGotON7u7sT7OY6yeCSFAp9rChnugAJ5pESZ7dmksf7aPQhFVzvlJejJKyk00OcGlzdW5CnGuETj/t5xS5rulxejqD++rG4Fr+2XnWLNKBbsA7JKKKQk0en7aQ034Hnp9kCPenHQMXTBuLJNfRnJOOuSeYQ6jbmoGgXuyvD+UzV6fscu0heX9mmTvb5wlXkciOmKZ1BGHtFdrX+DMbOJnNDBM6vN7PRdyIlaXUeffqrwVjwiKGk/qVjcHic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
